#
server:
  port: 8081
#
spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false